name: Deploy Health Monitor API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
              cd Server-health-monitor || exit 1

              git pull origin main

      
              sudo docker ps -q --filter "publish=3000" | xargs -r sudo docker stop || true
              sudo docker ps -aq --filter "publish=3000" | xargs -r sudo docker rm || true

              sudo docker stop health-container || true
              sudo docker rm health-container || true

              sudo docker build -t health-monitor-api .

              sudo docker run -d \
              --name health-container \
              -p 3000:3000 \
              --restart always \
               health-monitor-api
 